config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :banners
  resources :users
  resources :articles do
    resources :comments
  end
  resources :image
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  mount Commontator::Engine => '/commontator'
end

app/views/shared/_article.html.slim
-counter=0
-locals[:obj].each do |posts,itn|
  -counter=counter+1
  div class="row"
    div class="col-xs-8 col-xs-offset-2"
      div class="well well-lg"
        div class="article-title"
          = link_to posts.title, article_path(posts)
        div class="article-body"
          = truncate(posts.description, length: 100) 
          div class="article-meta-details"
            small
                | Created by:
                = posts.user.username if posts.user
                = time_ago_in_words(posts.created_at)+" "
                |ago,
                | last updated: 
                = time_ago_in_words(posts.updated_at)+" "
                | ago
                | Number of views: 
                = posts.hits 
        div
          =if current_user.id == posts.user_id
            div class="article-actions"
              = link_to "Edit", edit_article_path(posts), class: "btn btn-xs btn-primary" 
              = link_to "Delete", article_path(posts), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger"
  -if counter==locals[:row]
    a href==@randam_banner.link
      div align="center"
        div class="row"
          div class="col-xs-8 col-xs-offset-2"
            div class="box"
              =image_tag(@randam_banner.banner_image,class:"image")
              div class="text"
                  h2
                    =locals[:ads].title
                  p
                    =locals[:ads].description

app/views/shared/_errors.html.slim
-if obj.errors.any?
    div class="row"
        div class="col-xs-8 col-xs-offset-2"
            div class="panel panel-danger"
                div class="panel-heading"
                    h2 class="panel-title"
                    = pluralize(obj.errors.count, "error")
                    prohibited this object from being saved:
                    div class="panel-body"
                        ul
                            =obj.errors.full_messages.each do |msg|
                                li
                                    ==msg 

app/views/shared/_messages.html.slim
div class="row"
    div class="col-xs-10 col-xs-offset-1"
        -flash.each do |name, msg|
            div class='alert alert-"#{name}"'
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                =content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)