config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :banners
  resources :users
  resources :articles do
    resources :comments
  end
  resources :image
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  mount Commontator::Engine => '/commontator'
end

app/views/layouts/_navigation.html.slim
nav class="navbar navbar-default"
  div class="container-fluid"
    div class="navbar-header"
      button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"
        span class="sr-only"
        span class="icon-bar"
        span class="icon-bar">
        span class="icon-bar"
      = link_to "Blog", root_path, class: "navbar-brand", id: "logo"
    -if logged_in?
      div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"
        ul class="nav navbar-nav"
          li
            = link_to "Articles", articles_path
          li 
            = link_to "Create Article", new_article_path 
        ul class="nav navbar-nav navbar-right"
          li class="dropdown"
            a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              =current_user.username
              span class="caret"
            ul class="dropdown-menu"
              li role="separator" class="divider"
              li 
                = link_to "Settings", edit_user_path(:id => current_user.id)
              li role="separator" class="divider"
              li
                = link_to "Log out", logout_path, method: :delete
    -else
      div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"
        ul class="nav navbar-nav navbar-right"
          li
            = link_to "login", "login"
          li
            = link_to "SignUp", "signup"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Blog
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navigation'
    = render 'shared/messages' 

    = yield 